### CREATE CAMPAIGN
POST http://localhost:5005/campaign-api/create
Content-Type: application/json

{
  "title": "Urgent Medical Help",
  "description": "Need funds for surgery",
  "category": "Medical",
  "goalAmount": 50000,
  "deadline": "2026-12-31",
  "location": "Hyderabad"
}

### GET ALL APPROVED CAMPAIGNS
GET http://localhost:5005/campaign-api/

### SEARCH CAMPAIGNS
GET http://localhost:5005/campaign-api/?search=medical

### GET SINGLE CAMPAIGN
GET http://localhost:5005/campaign-api/PUT_CAMPAIGN_ID_HERE

### UPDATE CAMPAIGN
PUT http://localhost:5005/campaign-api/update/PUT_CAMPAIGN_ID_HERE
Content-Type: application/json

{
  "title": "Updated Campaign Title",
  "description": "Updated Description"
}

### DELETE CAMPAIGN
DELETE http://localhost:5005/campaign-api/delete/PUT_CAMPAIGN_ID_HERE