### CREATE CAMPAIGN

POST http://localhost:5005/campaign-api/create
Content-Type: application/json

{
  "title": "Urgent help needed for keerthan",
  "description": "Need funds",
  "goalAmount": 50000,
  "deadline": "2026-12-31",
  "createdBy": "69f97e4c5ee87fa0030aaad4"
}

### GET ALL APPROVED CAMPAIGNS

GET http://localhost:5005/campaign-api/campaigns/


### GET SINGLE CAMPAIGN

GET http://localhost:5005/campaign-api/campaigns/CAMPAIGN_ID


### APPROVE CAMPAIGN (ADMIN)


PUT http://localhost:5005/campaign-api/campaigns/approve/69f9bda317ccaf9aac9504dc


### UPDATE CAMPAIGN

PUT http://localhost:5005/campaign-api/campaigns/update/CAMPAIGN_ID
Content-Type: application/json

{
  "title": "Updated Campaign Title",
  "goalAmount": 75000
}

### SEARCH MEDICAL
GET http://localhost:5005/campaign-api/?search=keerthan


### DELETE CAMPAIGN

DELETE http://localhost:5005/campaign-api/campaigns/delete/CAMPAIGN_ID


### GET CAMPAIGNS BY USER

GET http://localhost:5005/campaign-api/campaigns/user/USER_ID