### REGISTER ROUTE
POST http://localhost:5005/auth-api/users
Content-Type: application/json

{
    "name" : "admin",
    "email" : "admin@gmail.com",
    "password" : "12345",
    "role" : "ADMIN"
}
### LOGIN ROUTE
POST http://localhost:5005/auth-api/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "user1"
}

### LOGOUT ROUTE
GET http://localhost:5005/auth-api/logout
### GET USER DETAILS
GET http://localhost:5005/user-api/users
###
DELETE  http://localhost:5005/user-api/users
###update password
PUT http://localhost:5005/user-api/users/password
Content-Type: application/json

{
    "oldPassword":"123",
    "newPassword":"1234"
}
###update profile
PUT http://localhost:5005/user-api/users
Content-Type: application/json

{
    "name":"keerthanReddy",
    "email":"keerthanReddy@gmail.com"
}
